"""Schema 模块导出常用类型，便于外部引用。"""

from app.schemas.auth import (
    AuthLoginRequest,
    AuthTokenPair,
    AuthenticatedResponse,
    LogoutRequest,
    PasswordChangeRequest,
    TokenIntrospectionResponse,
    TokenRefreshRequest,
)
from app.schemas.common import (
    ErrorResponse,
    IDMixin,
    ORMBaseModel,
    PaginatedResponse,
    PaginationMeta,
    TimestampMixin,
)
from app.schemas.members import (
    InvitationAcceptRequest,
    InvitationAcceptResponse,
    MemberInvitationCreate,
    MemberInvitationRead,
    TenantMemberCreate,
    TenantMemberRead,
    TenantMemberSummary,
    TenantMemberUpdate,
)
from app.schemas.applications import (
    AttachmentSchema,
    TenantApplicationRead,
    TenantApplicationReview,
    TenantApplicationSubmit,
    TenantApplicationSummary,
)
from app.schemas.orders import (
    SubscriptionOrderCreate,
    SubscriptionOrderProcess,
    SubscriptionOrderRead,
    SubscriptionOrderSummary,
)
from app.schemas.subscriptions import (
    SubscriptionPlanCreate,
    SubscriptionPlanRead,
    SubscriptionPlanUpdate,
    TenantSubscriptionCreate,
    TenantSubscriptionRead,
    TenantSubscriptionUpdate,
)
from app.schemas.tenants import (
    TenantBase,
    TenantCreate,
    TenantPlanUpdate,
    TenantRead,
    TenantStatusUpdate,
    TenantSummary,
    TenantUpdate,
)
from app.schemas.users import (
    CurrentUser,
    UserCreate,
    UserRead,
    UserUpdate,
)

__all__ = (
    "AuthLoginRequest",
    "AuthTokenPair",
    "AuthenticatedResponse",
    "LogoutRequest",
    "PasswordChangeRequest",
    "TokenIntrospectionResponse",
    "TokenRefreshRequest",
    "ErrorResponse",
    "IDMixin",
    "ORMBaseModel",
    "PaginatedResponse",
    "PaginationMeta",
    "TimestampMixin",
    "InvitationAcceptRequest",
    "InvitationAcceptResponse",
    "MemberInvitationCreate",
    "MemberInvitationRead",
    "TenantMemberCreate",
    "TenantMemberRead",
    "TenantMemberSummary",
    "TenantMemberUpdate",
    "AttachmentSchema",
    "TenantApplicationRead",
    "TenantApplicationReview",
    "TenantApplicationSubmit",
    "TenantApplicationSummary",
    "SubscriptionOrderCreate",
    "SubscriptionOrderProcess",
    "SubscriptionOrderRead",
    "SubscriptionOrderSummary",
    "SubscriptionPlanCreate",
    "SubscriptionPlanRead",
    "SubscriptionPlanUpdate",
    "TenantSubscriptionCreate",
    "TenantSubscriptionRead",
    "TenantSubscriptionUpdate",
    "TenantBase",
    "TenantCreate",
    "TenantPlanUpdate",
    "TenantRead",
    "TenantStatusUpdate",
    "TenantSummary",
    "TenantUpdate",
    "CurrentUser",
    "UserCreate",
    "UserRead",
    "UserUpdate",
)
