"""Add users model

Revision ID: 04e68006f9ae
Revises: 
Create Date: 2025-10-24 23:59:25.643188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e68006f9ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户主键，使用 UUID 确保跨系统唯一'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='用户邮箱，作为登录凭据'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希，使用 PBKDF2 等算法'),
    sa.Column('phone_number', sa.String(length=32), nullable=True, comment='手机号，便于短信或多因素认证'),
    sa.Column('display_name', sa.String(length=150), nullable=True, comment='展示名称，用于界面显示昵称'),
    sa.Column('full_name', sa.String(length=150), nullable=True, comment='用户真实姓名或企业联系人姓名'),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True, comment='头像地址，指向对象存储或 CDN'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账户是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否为平台管理员'),
    sa.Column('is_locked', sa.Boolean(), nullable=False, comment='是否因安全原因临时锁定'),
    sa.Column('timezone', sa.String(length=64), nullable=False, comment='时区信息，便于通知与报表'),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True, comment='最后一次修改密码时间'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='连续登录失败次数'),
    sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次登录失败时间'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后一次登录时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
