"""Add Tenant model

Revision ID: 27977169fd1f
Revises: 04e68006f9ae
Create Date: 2025-10-25 00:10:26.097538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27977169fd1f'
down_revision: Union[str, None] = '04e68006f9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False, comment='租户主键，UUID 确保全局唯一'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='租户名称'),
    sa.Column('slug', sa.String(length=120), nullable=False, comment='租户唯一标识，用于子域或路径'),
    sa.Column('primary_owner_id', sa.UUID(), nullable=False, comment='租户拥有者用户 ID'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'ARCHIVED', name='tenant_status'), nullable=False, comment='租户当前状态'),
    sa.Column('plan_code', sa.Enum('FREE', 'PRO', name='tenant_plan_code'), nullable=False, comment='当前订阅套餐'),
    sa.Column('member_limit', sa.Integer(), nullable=False, comment='成员数量上限，根据套餐设定'),
    sa.Column('contact_name', sa.String(length=120), nullable=False, comment='租户主要联系人姓名'),
    sa.Column('contact_email', sa.String(length=320), nullable=False, comment='联系人邮箱'),
    sa.Column('contact_phone', sa.String(length=32), nullable=False, comment='联系人电话'),
    sa.Column('timezone', sa.String(length=64), nullable=False, comment='租户所在时区，用于通知与报表'),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True, comment='租户激活时间'),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True, comment='租户停用时间'),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True, comment='试用结束时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='运营备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.CheckConstraint('member_limit > 0', name='ck_tenants_member_limit_positive'),
    sa.ForeignKeyConstraint(['primary_owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tenants_name'),
    sa.UniqueConstraint('slug', name='uq_tenants_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    # ### end Alembic commands ###
