"""Add all model

Revision ID: 32ebbf1ca8e7
Revises: 27977169fd1f
Create Date: 2025-10-25 00:53:29.783140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ebbf1ca8e7'
down_revision: Union[str, None] = '27977169fd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False, comment='套餐主键'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='套餐唯一代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='套餐展示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='套餐描述'),
    sa.Column('member_limit', sa.Integer(), nullable=False, comment='成员上限'),
    sa.Column('api_quota_per_month', sa.Integer(), nullable=False, comment='月度 API 调用配额，0 表示不限'),
    sa.Column('price_cents', sa.Integer(), nullable=False, comment='套餐价格（分）'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='货币编码'),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', 'LIFETIME', name='subscription_plan_billing_cycle'), nullable=False, comment='计费周期'),
    sa.Column('trial_days', sa.Integer(), nullable=False, comment='试用天数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用该套餐'),
    sa.Column('features', sa.JSON(), nullable=True, comment='套餐功能点描述（结构化数据）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.CheckConstraint('api_quota_per_month >= 0', name='ck_subscription_plan_quota_non_negative'),
    sa.CheckConstraint('member_limit > 0', name='ck_subscription_plan_member_limit_positive'),
    sa.CheckConstraint('price_cents >= 0', name='ck_subscription_plan_price_non_negative'),
    sa.CheckConstraint('trial_days >= 0', name='ck_subscription_plan_trial_days_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_subscription_plan_code')
    )
    op.create_table('member_invitations',
    sa.Column('id', sa.UUID(), nullable=False, comment='邀请记录主键'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='目标租户 ID'),
    sa.Column('invited_by_id', sa.UUID(), nullable=True, comment='邀请发起者用户 ID'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='member_invitation_role'), nullable=False, comment='邀请预设角色'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='受邀成员邮箱'),
    sa.Column('token', sa.String(length=128), nullable=False, comment='邀请校验 Token'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='member_invitation_status'), nullable=False, comment='邀请当前状态'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='邀请过期时间'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='邀请被接受时间'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='邀请被撤销时间'),
    sa.Column('message', sa.Text(), nullable=True, comment='附言或备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_member_invitation_email'),
    sa.UniqueConstraint('token', name='uq_member_invitation_token')
    )
    op.create_table('subscription_orders',
    sa.Column('id', sa.UUID(), nullable=False, comment='订单主键'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='关联租户 ID'),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True, comment='订单申请人（租户管理员）'),
    sa.Column('processed_by_user_id', sa.UUID(), nullable=True, comment='订单处理人（平台管理员）'),
    sa.Column('current_plan_id', sa.UUID(), nullable=True, comment='当前套餐 ID'),
    sa.Column('target_plan_id', sa.UUID(), nullable=True, comment='目标套餐 ID'),
    sa.Column('current_plan_code', sa.String(length=50), nullable=False, comment='当前套餐代码（冗余）'),
    sa.Column('target_plan_code', sa.String(length=50), nullable=False, comment='目标套餐代码（冗余）'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PAID', 'CANCELLED', name='subscription_order_status'), nullable=False, comment='订单状态'),
    sa.Column('amount_cents', sa.Integer(), nullable=False, comment='应付金额（分）'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='货币编码'),
    sa.Column('payment_reference', sa.String(length=120), nullable=True, comment='线下支付凭证号/备注'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='订单处理时间'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='支付确认时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='本次订阅到期时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='运营备注'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='附加信息（对账、附件等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['current_plan_id'], ['subscription_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_plan_id'], ['subscription_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_applications',
    sa.Column('id', sa.UUID(), nullable=False, comment='申请记录主键'),
    sa.Column('company_name', sa.String(length=200), nullable=False, comment='申请企业名称'),
    sa.Column('contact_name', sa.String(length=120), nullable=False, comment='联系人姓名'),
    sa.Column('contact_email', sa.String(length=320), nullable=False, comment='联系人邮箱'),
    sa.Column('contact_phone', sa.String(length=32), nullable=False, comment='联系人电话'),
    sa.Column('business_description', sa.Text(), nullable=True, comment='业务简介或申请说明'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件信息（例如证照、截图的链接）'),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True, comment='提交人用户 ID（如已注册）'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='对应创建的租户 ID（审核通过后填入）'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='tenant_application_status'), nullable=False, comment='申请当前状态'),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True, comment='平台审核人用户 ID'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='审核时间'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='驳回原因'),
    sa.Column('notes', sa.Text(), nullable=True, comment='运营备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_members',
    sa.Column('id', sa.UUID(), nullable=False, comment='租户成员记录主键'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='关联租户 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户 ID'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='tenant_member_role'), nullable=False, comment='成员角色'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'REMOVED', name='tenant_member_status'), nullable=False, comment='成员状态'),
    sa.Column('invited_by_id', sa.UUID(), nullable=True, comment='邀请者用户 ID'),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True, comment='成员激活时间'),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True, comment='成员被停用或移除时间'),
    sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True, comment='最后一次访问时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='运营或备注信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_member')
    )
    op.create_table('tenant_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False, comment='订阅记录主键'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='关联租户 ID'),
    sa.Column('plan_id', sa.UUID(), nullable=True, comment='关联订阅套餐 ID'),
    sa.Column('plan_code', sa.String(length=50), nullable=False, comment='订阅套餐代码（冗余存储）'),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', name='tenant_subscription_status'), nullable=False, comment='当前订阅状态'),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True, comment='订阅开始时间'),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True, comment='订阅结束时间'),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True, comment='试用结束时间'),
    sa.Column('cancel_at', sa.DateTime(timezone=True), nullable=True, comment='取消生效时间'),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False, comment='是否在当前账期结束时取消'),
    sa.Column('auto_renew', sa.Boolean(), nullable=False, comment='是否开启自动续费'),
    sa.Column('member_limit', sa.Integer(), nullable=False, comment='该周期的成员上限'),
    sa.Column('price_cents', sa.Integer(), nullable=False, comment='实际金额（分）'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='结算币种'),
    sa.Column('activated_by_user_id', sa.UUID(), nullable=True, comment='激活操作人'),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True, comment='取消操作人'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['activated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_subscriptions')
    op.drop_table('tenant_members')
    op.drop_table('tenant_applications')
    op.drop_table('subscription_orders')
    op.drop_table('member_invitations')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
