"""Initial migration

Revision ID: 682a9dd0ce8b
Revises: 
Create Date: 2025-10-21 03:29:06.828569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682a9dd0ce8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False, comment='租户唯一标识符'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='租户名称（公司或组织名称）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='租户是否激活'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除（软删除）'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='租户表 - 支持多租户数据隔离'
    )
    op.create_index('ix_tenants_active_not_deleted', 'tenants', ['is_active', 'is_deleted'], unique=False)
    op.create_index('ix_tenants_created_at', 'tenants', ['created_at'], unique=False)
    op.create_index('ix_tenants_is_active', 'tenants', ['is_active'], unique=False)
    op.create_index('ix_tenants_is_deleted', 'tenants', ['is_deleted'], unique=False)
    op.create_index('ix_tenants_name', 'tenants', ['name'], unique=False)
    op.create_index('ix_tenants_name_active', 'tenants', ['name', 'is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户唯一标识符'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='用户姓名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='电子邮箱地址（唯一）'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='加密后的密码'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账户是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否为超级用户（跨租户权限）'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tenants_name_active', table_name='tenants')
    op.drop_index('ix_tenants_name', table_name='tenants')
    op.drop_index('ix_tenants_is_deleted', table_name='tenants')
    op.drop_index('ix_tenants_is_active', table_name='tenants')
    op.drop_index('ix_tenants_created_at', table_name='tenants')
    op.drop_index('ix_tenants_active_not_deleted', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
