"""Initial migration

Revision ID: c2b78b30deb2
Revises: 
Create Date: 2025-10-21 00:36:19.666693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b78b30deb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False, comment='租户唯一标识符'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='租户名称（公司或组织名称）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户唯一标识符'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='用户姓名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='电子邮箱地址（唯一）'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='加密后的密码'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账户是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否为超级用户（跨租户权限）'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
