"""Add is_deleted and deleted_at fields to users table

Revision ID: d9d0c134cd87
Revises: 682a9dd0ce8b
Create Date: 2025-10-21 12:06:06.841851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d0c134cd87'
down_revision: Union[str, Sequence[str], None] = '682a9dd0ce8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除（软删除标记）'))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
