version: '1.0'
name: pipeline-20251018
displayName: pipeline-20251018
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-f45e0e27
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: crpi-iyq1iqfffn9ehscp.cn-beijing.personal.cr.aliyuncs.com/eaglelzy/saas_platform
        username: eagle_lzy@dev.csdn.net
        password: Lzy142857
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
